# schema.yml file contains all the generic and custom generic tests 
version: 2
models:
  - name: dim_listings_cleansed # Model name
    description: Cleansed table which contains airbnb listings  #for doucmentation purpose  
    columns:
      - name: listing_id        # Columnm name
        tests:                  # Type of generic/custom generic tests to run against the column
          - unique
          - not_null
      - name: host_id
        description: The host's id. Reference to hosts table
        tests:
          - not_null
          - relationships:
              to: ref('dim_hosts_cleansed')
              field: host_id
      - name: room_type
        description: Type of apartment / room
        tests:
          - accepted_values:
              values: ['Entire home/apt',
              'Private room',
              'Shared room',
              'Hotel room']
      - name: minimum_nights
        description: '{{ doc("dim_listing_cleansed__minimum_nights") }}'
        tests:
          - positive_value    # This is an example of custom generic test. The test is defined at macros/positive_value.sql
  - name: dim_hosts_cleansed
    description: Cleansed table for the Airbnb hosts
    columns:
      - name: host_id
        description: The id of the host. This is the primary key.
        tests:
          - not_null
          - unique
      
      - name: host_name
        description: The name of the host
        tests:
          - not_null
      
      - name: is_superhost
        description: Defines whether the hosts is a superhost.
        tests:
          - accepted_values:
              values: ['t', 'f']
  
