# sources.yml file contains all the information of source/raw tables.
# it can also be used to define the freshness of source tables.
# eg. warn_after: {count: 1, period: hour} In this case, dbt checks max value of 'loaded_at_field' and if it is older than 1 hour. dbt will throw an error
version: 2
sources:
  - name: airbnb
    schema: raw
    tables:
      - name: listings
        identifier: raw_listings
        columns:
          - name: room_type
            tests: 
              - dbt_expectations.expect_column_distinct_count_to_equal:
                  value: 4 # Here I am saying, for room_type column, distinct values should be 4 
          - name: price
            tests:
              - dbt_expectations.expect_column_values_to_match_regex:
                  regex: "^\\\\$[0-9][0-9\\\\.]+$"
                  # $ and . are reserved chars in regex, so you need back slash to escape it.
                  # back slash is reserved char in yaml so you need another backslash to avoid it
                  # back slash is also reserved char in snowflake so you need to have another 2 backslash to keep the 2 backslash at snowflake level
      - name: hosts
        identifier: raw_hosts

      - name: reviews
        identifier: raw_reviews
        loaded_at_field: date
        freshness: 
          warn_after: {count: 1, period: hour}
          error_after: {count: 1, period: day}
